# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

name: iot-sensor-network

services:
  client-static-web:
    build:
      context: ../applications/client-static-web
      dockerfile: Containerfile
    ports:
      - 8080:80

  server:
    build:
      context: ../applications/server
      dockerfile: Containerfile
    environment:
      HOST: "server"
    ports:
      - 9090:80
      - 9091:443
    volumes:
      - temperature:/data
    networks:
      - backbone

  sensor-temperature:
    build:
      context: ../applications/sensor-temperature
      dockerfile: Containerfile
    environment:
      WEATHER_ADDRESS: "http://server:80"
    networks:
      - backbone
    depends_on:
      - server
    deploy:
      replicas: 5

networks:
  backbone:
