# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

name: iot-sensor-network

services:
  client-static-web:
    build:
      context: ../applications/client-static-web
      dockerfile: Containerfile
    ports:
      - 8080:80

