FROM node:22.2.0-alpine3.20 as base

FROM base as production-dependencies
WORKDIR /workspace
COPY package.json package-lock.json  /workspace
RUN npm clean-install

FROM base as production
WORKDIR /app

COPY --from=production-dependencies /workspace/node_modules /app/node_modules
COPY --from=production-dependencies /workspace/package.json /app/package.json
COPY src /app/src

ENTRYPOINT ["node", "/app/src/main.js"]