FROM node:22.2.0-alpine3.20 as base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base as development-dependencies
WORKDIR /workspace
COPY package.json pnpm-lock.yaml  /workspace
RUN pnpm install --frozen-lockfile

FROM base as builder
WORKDIR /workspace

COPY --from=development-dependencies /workspace/node_modules /workspace/node_modules
COPY --from=development-dependencies /workspace/package.json /workspace/package.json
COPY . /workspace

RUN pnpm run build

FROM joseluisq/static-web-server:2 as static-server
COPY --from=builder /workspace/dist /public